name: data
on:
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    env: 
      SSL_CERT_DIR: /etc/ssl/certs
    steps:
      - name: download cert
        run: |
          echo '::echo::on'
          sudo curl https://gogetssl-cdn.s3.eu-central-1.amazonaws.com/wiki/gogetssl-rsa-dv-ca.crt > /etc/ssl/certs/gogetssl.crt
      - name: chmod cert 
        run: sudo chmod 644 /etc/ssl/certs/gogetssl.crt
      - name: update ca
        run: sudo update-ca-certificates
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: http://tr.mos.ru/widget-gin/api/ginobjects
          downloaded_filename: designated-use-checks/data/2021/ginobjects.json
          axios_config: designated-use-checks/config/axios-config-2021.json
          postprocess: designated-use-checks/scripts/process-response.js
