name: data
on:
  schedule:
    - cron: 0 15 * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
jobs:
  scheduled:
    runs-on: ubuntu-latest
    env: 
      # tr.mos.ru's certificate chain is broken
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Fetch data
        uses: githubocto/flat@v3
        with:
#           http_url: https://tr.mos.ru/widget-gin/api/ginobjects
#           axios_config: designated-use-checks/config/axios-config-2021.json
          downloaded_filename: designated-use-checks/data/2021/ginobjects.json
          postprocess: designated-use-checks/scripts/process-response.js
#       - name: run postprocess script
#         run: deno run -q -A --unstable designated-use-checks/scripts/process-response.js designated-use-checks/scripts/process-response.js
